void forward(int ltps, int rtps, int distance);
void backward(int ltps,int rpts, int distance);
void pright(int distance);
void pleft(int distance);
void right(int distance);
void left(int distance);
void pause(int time);
void slowservo(int startposition, int servonumber, int counter, int counterspeed);
void servototop();
void ssp(int time, int port, int position);
void forsquare();
void backsquare();
void follow(int distance);
void bfollow(int distance);
void wfl(int port);
void sdi(int time);
